# application.yml - Configuração Segura e Profissional
spring:
  application:
    name: digital-bank-api

  datasource:
    url: jdbc:mysql://localhost:3306/digital_bank_api
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update} # Usar 'validate' em produção
    show-sql: ${SHOW_SQL:false}    # Desabilitado por padrão
    database-platform: org.hibernate.dialect.MySQL8Dialect

  profiles:
    active: ${SPRING_PROFILE:dev}

rendimento:
  poupanca:
    taxa-mensal: ${TAXA_RENDIMENTO:0.005} # 0.5% ao mês

jwt:
  secret: ${JWT_SECRET} # ✅ OBRIGATÓRIO via variável de ambiente
  expiration: ${JWT_EXPIRATION:3600000} # 1 hora (mais seguro)

logging:
  level:
    com.wallace.spring.boot: INFO
    org.springframework.security: WARN
    org.springframework.web: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    
---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true
  logging:
    level:
      com.wallace.spring.boot: DEBUG

---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  logging:
    level:
      root: WARN
      com.wallace.spring.boot: INFO